enhance/VCMS85
blackMisay/vet-management pull request #87
Opened 2024-11-15 17:31 UTC by lhyra13

I am done with adding a button in the product modal to add a new category and type. Could you check if it's correct? thanyou

2024-11-15 21:41 UTC, lhyra13 commented
Also added a new form of frmAddNewColor and frmAddNewSpecie with function.

2024-11-17 06:12 UTC, blackMisay requested changes
Here is my review:
- After inserting new breed or color, DO NOT call the frmClientPatientModal again, instead populate the combobox after closing the frmNewPetColor/frmNewBreed.
- Fix the incorrect data in `Breed` combobox - when adding New Pet in Client module, the breed combobox data is populated both from Cat and Dog breed.

2024-11-17 06:12 UTC, blackMisay commented on app/View/Client/frmNewPetColor.cs
> +        private void label1_Click(object sender, EventArgs e)
Remove unnecessary event methods

2024-11-18 02:21 UTC, blackMisay approved these changes

2024-11-18 03:09 UTC, merged